# Generated by Django 4.2.13 on 2025-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_question_answer_question_is_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_group', models.CharField(blank=True, max_length=255, null=True)),
                ('no_group', models.BooleanField(default=True)),
            ],
        ),
    ]
