# Generated by Django 4.2.13 on 2025-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
