# Generated by Django 4.2.13 on 2025-01-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_question_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='program',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
